---
# tasks file for ansible-pgbouncer

- name: install | add apt key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present
  register: pgbouncer_apt_key

- name: install | add repos
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
  register: pgbouncer_apt_sourcelist

- name: install | update package cache
  apt:
    update_cache: yes
  when:
    - pgbouncer_apt_sourcelist.changed or pgbouncer_apt_key.changed

- name: install | install package
  apt:
    name:
      - "{{ pgbouncer_package }}{% if pgbouncer_version | bool and pgbouncer_version != 'latest' %}={{ pgbouncer_version }}*{% endif %}"
    state: latest
    install_recommends: yes
    force: yes
    force_apt_get: yes
    dpkg_options: "{{ dpkg_force_overwrite_configs | ternary('force-confdef,force-confnew', 'force-confdef,force-confold') }}"
    update_cache: yes
    cache_valid_time: 3600
  environment:
    DEBIAN_FRONTEND: noninteractive
    RUNLEVEL: 1
