---
# tasks file for ansible-pgbouncer

- include_tasks: debian.yml
  when:
    - ansible_os_family == 'Debian'
  tags:
    - always

- include_tasks: systemd.yml
  when:
    - ansible_service_mgr == 'systemd'
  tags:
    - always

- include_tasks: sysvinit.yml
  when:
    - ansible_service_mgr != 'systemd'
  tags:
    - always

- include_tasks: configure.yml
  tags:
    - always

- meta: flush_handlers
