---
- name: service | check override path
  file:
    path: /etc/systemd/system/pgbouncer.service.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: service | create systemd service override file
  template:
    src: etc/systemd/system/pgbouncer.service.d/override.conf.j2
    dest: /etc/systemd/system/pgbouncer.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd config
