---
# handlers file for ansible-pgbouncer

- name: reload systemd config
  systemd:
    daemon_reload: yes
  notify:
    - restart pgbouncer
  when:
    - ansible_service_mgr == 'systemd'

- name: handle pgbouncer service state is "{{ pgbouncer_restarted_state }}"
  service:
    name: pgbouncer
    enabled: yes
    state: "{{ pgbouncer_restarted_state }}"
  listen:
    - restart pgbouncer

- name: wait for port "{{ pgbouncer_listen_port }}" to become open on the host
  wait_for:
    port: "{{ pgbouncer_listen_port }}"
    host: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    state: started
    timeout: 120
    delay: 5
  ignore_errors: false
  listen:
    - restart pgbouncer
