---
# handlers file for ansible-pgbouncer

- name: to be sure that systemd config is reload
  systemd:
    daemon_reload: true
  listen:
    - restart pgbouncer
  when:
    - ansible_service_mgr == 'systemd'

- name: handle pgbouncer service state is 'pgbouncer_service_state'
  service:
    name: pgbouncer
    state: "{{ pgbouncer_service_state }}"
    enabled: true
  listen:
    - restart pgbouncer

- name: wait for 'pgbouncer_listen_port' to become open on the host
  wait_for:
    host: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    port: "{{ pgbouncer_listen_port }}"
    state: started
    timeout: 120
    delay: 5
  ignore_errors: false
  when:
    - pgbouncer_service_state != 'stopped'
  listen:
    - restart pgbouncer
