---
# handlers file for ansible-pgbouncer

- name: reload systemd config
  systemd:
    daemon_reload: yes
  notify:
    - restart pgbouncer
  when:
    - ansible_service_mgr == 'systemd'

- name: restart pgbouncer
  service:
    name: pgbouncer
    enabled: yes
    state: "{{ pgbouncer_restarted_state }}"
